port: /dev/ttyUSB1
read_rate: 15
write_rate: 25
dynamixels: {
    shoulder_pan_joint: {id: 1, neutral: 150, max_angle: 150, min_angle: -150, max_speed: 90},
    shoulder_lift_joint: {id: 2, max_angle: 150, min_angle: -150, max_speed: 90},
    elbow_flex_joint: {id: 3, max_angle: 150, min_angle: -150, max_speed: 90},
    wrist_flex_joint: {id: 4, max_angle: 150, min_angle: -150, max_speed: 90},
    gripper_joint: {id: 5, max_speed: 90},
}
controllers: {
    arm_controller: {type: follow_controller, joints: [shoulder_pan_joint, shoulder_lift_joint, elbow_flex_joint, wrist_flex_joint] }
}
